# Generated by Django 4.1.9 on 2023-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runDiagram", "0005_remove_runninglap_endlapday"),
    ]

    operations = [
        migrations.AddField(
            model_name="runninglap",
            name="numberOfLaps",
            field=models.IntegerField(default=0, verbose_name="Liczba okrazen"),
        ),
    ]
