# Generated by Django 4.1.9 on 2023-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runChart", "0002_alter_runninglap_endlaptime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runninglap",
            name="endLapTime",
            field=models.TimeField(verbose_name="Czas zakonczenia okrazenia"),
        ),
    ]
