# Generated by Django 4.1.9 on 2023-09-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runChart", "0004_runninglap_endlapday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runninglap",
            name="endLapDay",
        ),
    ]
