# Generated by Django 4.2.5 on 2023-09-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runChart", "0008_remove_time_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runninglap",
            name="endLapDate",
            field=models.DateTimeField(verbose_name="Data zakonczenia okrazenia"),
        ),
    ]
