# Generated by Django 4.2.5 on 2023-09-26 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runChart", "0009_remove_default_dateTime"),
    ]

    operations = [
        migrations.AddField(
            model_name="runninglap",
            name="startLapDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 21, 21, 30),
                verbose_name="Data rozpoczecia okrazenia",
            ),
        ),
        migrations.AlterField(
            model_name="runninglap",
            name="endLapDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 22, 9, 30),
                verbose_name="Data zakonczenia okrazenia",
            ),
        ),
    ]
