# Generated by Django 4.2.5 on 2023-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runChart', '0012_endLapDateNull'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
