# Generated by Django 4.2.5 on 2024-10-31 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runChart', '0013_runner_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runninglap',
            name='startLapDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 21, 30), verbose_name='Data rozpoczecia okrazenia'),
        ),
    ]
