# Generated by Django 4.2.5 on 2025-10-16 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runChart', '0014_changeDefaultStartTime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runninglap',
            name='startLapDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 21, 30), verbose_name='Data rozpoczecia okrazenia'),
        ),
    ]
